name: Email Health # Name of the GitHub Actions workflow shown in the Actions tab

on: # Defines when this workflow should be triggered
  schedule: # Scheduled automatic runs
    - cron: "*/30 * * * *" # Runs every 30 minutes using cron syntax
  workflow_dispatch: # Allows manual triggering of this workflow from the GitHub UI

jobs: # Defines the jobs that will be run in this workflow
  email_health_check: # Identifier for the job
    name: Email Health # Descriptive name of the job
    runs-on: ubuntu-latest # Specifies the runner environment for the job

    env: # Environment variables available to all steps in this job
      MXROUTE_EMAIL: ${{ secrets.MXROUTE_EMAIL }}
      MXROUTE_PASSWORD: ${{ secrets.MXROUTE_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
